# frozen_string_literal: true

# Hand-written, DEPRECATED Homebrew formula for the Builder -> Kent migration.
#
# This is the canonical source for `Formula/builder-cli.rb` in the
# respawn-llc/homebrew-tap repo. It is published MANUALLY (copied into the tap),
# NOT regenerated by scripts/update-brew-tap.sh or the release workflow — those
# now only produce the `kent` formula.
#
# It installs the prebuilt Builder 2.0 migration-only compat binary from the
# builder-2.0.0 release of respawn-llc/kent (no source build / no toolchain).
# That binary refuses to start and only runs `builder migrate` and
# `builder service uninstall`.
#
# IMPORTANT: do NOT add `depends_on "kent"`. A dependency marks kent as
# installed-as-dependency, so a later `brew autoremove` (after the user
# uninstalls builder-cli) would delete the real kent binary. Users install kent
# explicitly. There is also intentionally NO post_install service-restart hook.
#
# Retirement: keep `deprecate!` (installable, warns) during the ~1-month
# migration window, then `disable!`, then remove the formula.
class BuilderCli < Formula
  desc "Migration-only build to move from Builder to Kent (deprecated)"
  homepage "https://kent.sh/"
  version "2.0.0"
  license "AGPL-3.0-only"

  # Replacement is the `kent` formula; users install it explicitly.
  disable! date: "2026-09-07", because: "was renamed to Kent; install `kent`"

  on_macos do
    on_arm do
      url "https://github.com/respawn-llc/kent/releases/download/builder-2.0.0/builder_2.0.0_darwin_arm64.tar.gz"
      sha256 "1775d3af3373082980613ebef1e0114e29ae7b09eafb3e99f852289b8b4bf535"
    end
    on_intel do
      url "https://github.com/respawn-llc/kent/releases/download/builder-2.0.0/builder_2.0.0_darwin_amd64.tar.gz"
      sha256 "f105b4f16df5e28c88dc4cd5be951cde155b04aed27aecb64fb19de71b3fdd34"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/respawn-llc/kent/releases/download/builder-2.0.0/builder_2.0.0_linux_arm64.tar.gz"
      sha256 "4c58a17a32f814e1863f3d401a141d3e6ae35d9377e4a57c5269da352fd6b0f8"
    end
    on_intel do
      url "https://github.com/respawn-llc/kent/releases/download/builder-2.0.0/builder_2.0.0_linux_amd64.tar.gz"
      sha256 "c13904b7dd4f4ac406c672fb485cdf15c926d1566e2993a80e1aeb389675257e"
    end
  end

  def install
    bin.install "builder"
  end

  def caveats
    <<~EOS
      Builder has been renamed to Kent. This is the migration-only build; it does
      not start a server or run agents.

      To migrate (run these yourself — migration is never automatic):
        1. Stop all Builder activity (interactive sessions, `builder serve`, and
           `builder service stop` if the background service is installed).
        2. Move + rebase your data:   builder migrate
        3. Install Kent:              brew install respawn-llc/homebrew-tap/kent
        4. Remove this formula:       brew uninstall builder-cli

      Migration guide: https://kent.sh/
    EOS
  end

  test do
    output = shell_output("#{bin}/builder 2>&1", 1)
    assert_match "renamed to Kent", output
  end
end
